require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'

target 'aniyoo' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

  pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'

  pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-async-storage/async-storage'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'

  pod 'react-native-viewpager', :path => '../node_modules/@react-native-community/viewpager'

  pod 'ReactNativeART', :path => '../node_modules/@react-native-community/art'

  pod 'RNSVG', :path => '../node_modules/react-native-svg'

  pod 'RNReanimated', :path => '../node_modules/react-native-reanimated'

  pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'

  pod 'rn-fetch-blob', :path => '../node_modules/rn-fetch-blob'


  pod 'RNSnackbar', :path => '../node_modules/react-native-snackbar'

  pod 'react-native-blur', :path => '../node_modules/@react-native-community/blur'

  pod 'RNImageCropPicker', :path => '../node_modules/react-native-image-crop-picker'



  pod 'RNCClipboard', :path => '../node_modules/@react-native-community/clipboard'

  target 'aniyooTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  use_flipper!()

  post_install do |installer|
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
end
